sudo: false
language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
  - jruby-9.2.0.0
before_install:
  - gem install bundler -v 1.16.1
git:
  submodules: false
gemfile:
  - Gemfile
matrix:
  include:
    - rvm: 2.5.1
      gemfile: gemfiles/rubyracer
    - rvm: jruby-9.2.0.0
      gemfile: gemfiles/rubyrhino
    - rvm: 2.5.1
      gemfile: gemfiles/alaska
      env: ALASKA=1
  allow_failures:
    - rvm: 2.5.1
      gemfile: gemfiles/alaska
      env: ALASKA=1
    - rvm: ruby-head
  fast_finish: true
