language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
env:
  - EXECJS_RUNTIME=RubyRacer
  - EXECJS_RUNTIME=RubyRhino
matrix:
  exclude:
    - rvm: 1.8.7
      env: EXECJS_RUNTIME=RubyRhino
    - rvm: 1.9.2
      env: EXECJS_RUNTIME=RubyRhino
    - rvm: 1.9.3
      env: EXECJS_RUNTIME=RubyRhino
    - rvm: 2.0.0
      env: EXECJS_RUNTIME=RubyRhino
    - rvm: jruby-18mode
      env: EXECJS_RUNTIME=RubyRacer
